import LegalPage from "../../components/LegalPage";

export default function DisclaimerPage() { return <LegalPage eyebrow="Important risk information" title="Financial and model disclaimer">
  <h2>Not financial advice</h2><p>Stoxcheck is provided solely for education, academic evaluation and general information. Nothing displayed is financial advice, investment advice, a personal recommendation, investment research, a trading signal, an offer or solicitation, or advice to buy, sell, subscribe for or hold any security or financial product.</p>
  <h2>No regulated relationship</h2><p>Using Stoxcheck does not create an adviser-client, fiduciary, brokerage or professional relationship. Stoxcheck is not presented as authorised by the UK Financial Conduct Authority. Seek advice from an appropriately authorised independent professional before making financial decisions.</p>
  <h2>Model limitations</h2><p>Sentiment is an automated estimate of language, not objective truth. The model can misunderstand negation, sarcasm, ambiguity, targets, quotations and specialist context. Accuracy measured on historic held-out data does not guarantee live accuracy. Confidence is a model probability, not the probability an investment will succeed.</p>
  <h2>Data limitations</h2><p>News can be missing, delayed, duplicated, incorrectly associated with a ticker, changed by a publisher or drawn from very few sources. A strong index based on two headlines is not equivalent to broad market consensus. Publisher links and timestamps should be checked directly.</p>
  <h2>No price prediction</h2><p>Positive news language does not imply a share price will rise; negative language does not imply it will fall. Prices react to expectations, valuation, liquidity, macroeconomic conditions and information not represented here. Past model performance and historical sentiment are not indicators of future returns.</p>
  <h2>Risk of loss</h2><p>Investments can fall as well as rise. You may lose some or all capital, and some products can produce losses exceeding the initial amount. Never rely on Stoxcheck as the sole basis for a decision. Verify information, assess suitability and risk, and obtain regulated advice where appropriate.</p>
  <h2>No warranty</h2><p>Outputs are supplied “as is” and may be unavailable or wrong. To the extent permitted by law, the operator accepts no responsibility for losses caused by reliance on sentiment, headlines, links or availability. Statutory rights and liabilities that cannot lawfully be excluded remain unaffected.</p>
  <h2>Financial promotions</h2><p>Stoxcheck does not intend its content to invite or induce investment activity. Any future commercial content, affiliate relationship, issuer promotion or specific call to action must undergo separate legal and regulatory review before publication. General FCA information is available at <a href="https://www.fca.org.uk/consumers" target="_blank" rel="noreferrer">fca.org.uk/consumers</a>.</p>
</LegalPage>; }
