import LegalPage from "../../components/LegalPage";

export default function PrivacyPage() { return <LegalPage eyebrow="Privacy" title="Privacy and data usage notice">
  <h2>1. Who controls the information</h2><p>Stoxcheck is an academic project operated from the United Kingdom. Privacy questions and rights requests should be directed to the project operator who issued the account credentials.</p>
  <h2>2. Information processed</h2><ul><li><strong>Account data:</strong> generic username, internal randomised Firebase identifier, Firebase user identifier, account status and authentication timestamps. No personal email address is requested.</li><li><strong>Authentication/security data:</strong> sign-in events, approximate network/device information and abuse/security records processed by Firebase/Google.</li><li><strong>Technical data:</strong> request time, route, response status, latency, browser/device metadata and IP-related logs processed by hosting providers.</li><li><strong>Submitted content:</strong> a headline voluntarily entered in the manual checker and the returned probabilities. Stoxcheck does not intentionally save this text to its application database, although normal short-lived infrastructure processing/log safeguards apply.</li><li><strong>News data:</strong> public publisher headlines, URLs, sources, timestamps and model outputs. These concern companies/news, not account profiles.</li></ul>
  <h2>3. Why it is used</h2><p>Information is used to authenticate the ten approved users, secure and operate the service, diagnose failures, prevent abuse, provide requested sentiment results, maintain aggregate analytics and demonstrate/evaluate the academic project.</p>
  <h2>4. Lawful bases</h2><p>Depending on the context, processing is necessary to provide the requested restricted service (contract), for legitimate interests in security, reliability, research and abuse prevention, or to comply with legal obligations. Where optional non-essential cookies or analytics are introduced, consent will be requested first.</p>
  <h2>5. Credentials</h2><p>Firebase Authentication handles passwords. Stoxcheck does not receive or store raw passwords in Firestore. Administrators can create, disable or reset the ten accounts using Firebase administrative controls. Do not send a password by email or include it in support messages.</p>
  <h2>6. Sharing and processors</h2><p>Information may be processed by Google Firebase/Cloud for authentication, API, logging and storage; Vercel for website hosting; and Finnhub for news requests made by the backend. Publisher links lead to separate controllers. Information may also be disclosed where required by law or necessary to protect systems and users.</p>
  <h2>7. International transfers</h2><p>Technology providers may process information outside the UK. Their contractual transfer safeguards and privacy terms apply. Provider documentation should be reviewed and recorded by the operator before a wider production launch.</p>
  <h2>8. Retention</h2><ul><li>Firebase account records are retained while an issued account remains active and then deleted or disabled according to project administration needs.</li><li>Recent news headline observations expire after approximately 90 minutes.</li><li>Deduplication hashes expire after approximately seven days.</li><li>Headline-free hourly, daily and weekly aggregate statistics are retained for long-term analysis.</li><li>Cloud and hosting security/operational logs follow provider-configured retention periods.</li><li>The terms acknowledgement is kept in browser session storage for the current login and is not used for advertising.</li></ul>
  <h2>9. Your rights</h2><p>UK data-protection law may provide rights of access, correction, erasure, restriction, objection and data portability, and the right to complain to the Information Commissioner’s Office. Rights depend on the circumstances and legal exceptions. Contact the project operator with enough information to identify the account.</p>
  <h2>10. Automated decision-making</h2><p>The model automatically classifies company-news wording. It does not make a legal or similarly significant decision about an account holder. Do not use its result to make significant decisions about a person.</p>
  <h2>11. Security</h2><p>Controls include Firebase Authentication, restricted service accounts, Secret Manager, HTTPS, deny-all browser database rules, input bounds and short headline retention. No internet service can promise absolute security.</p>
  <h2>12. Children</h2><p>Stoxcheck is not intended for children and accounts are restricted to users aged 18 or over.</p>
  <h2>13. Updates</h2><p>Material changes will update the date/version and be presented for acknowledgement at sign-in. UK privacy guidance is available from the <a href="https://ico.org.uk/for-the-public/" target="_blank" rel="noreferrer">Information Commissioner’s Office</a>.</p>
</LegalPage>; }
