# The collector is deployed as a Cloud Run Job.
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - Dockerfile.collector
      - --tag
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
