import LegalPage from "../../components/LegalPage";

export default function TermsPage() { return <LegalPage eyebrow="Legal" title="Terms and conditions">
  <h2>1. Agreement</h2><p>These terms govern access to Stoxcheck. By signing in, selecting “I understand and agree”, or using the service, you agree to these terms. If you do not agree, do not use Stoxcheck.</p>
  <h2>2. Eligibility and accounts</h2><p>You must be at least 18 and authorised to use one of the ten administrator-issued accounts. Keep credentials confidential, do not share an account, and notify the project operator if access may be compromised. Access may be suspended or withdrawn at any time for security, maintenance, misuse or project closure.</p>
  <h2>3. Experimental service</h2><p>Stoxcheck is an academic and experimental news-language analysis service. It estimates whether recent wording concerning a company appears positive, neutral or negative. It does not establish facts, predict prices, evaluate an investment or replace professional research.</p>
  <h2>4. Acceptable use</h2><p>You must not attempt unauthorised access; scrape, overload or disrupt the service; evade input or rate limits; reverse engineer credentials or security controls; upload unlawful, malicious or rights-infringing content; impersonate another person; or use outputs to mislead others. Automated or commercial reuse requires prior written permission.</p>
  <h2>5. Third-party material</h2><p>Headlines, links, company names and publisher names belong to their respective owners. Links lead to independent sites whose content, availability, security and policies Stoxcheck does not control. Finnhub, Firebase, Google Cloud and Vercel are independent service providers.</p>
  <h2>6. Intellectual property</h2><p>The Stoxcheck name, interface, original software and explanatory material are protected to the extent permitted by law. These terms grant only a limited, revocable, non-transferable right to use the service for personal evaluation and academic demonstration.</p>
  <h2>7. Availability and changes</h2><p>The service may be delayed, interrupted, changed or discontinued. News may be incomplete or duplicated; model outputs may be wrong; and historical values may change when systems or models change. No service level, uninterrupted availability or fitness for a particular purpose is promised.</p>
  <h2>8. Financial and professional disclaimer</h2><p>Nothing on Stoxcheck is financial, investment, trading, legal, accounting or tax advice, a recommendation, research report, offer, solicitation or endorsement. Do not buy, sell or hold an investment based on Stoxcheck. Obtain independent regulated advice and verify primary sources.</p>
  <h2>9. Liability</h2><p>Use is at your own risk. To the fullest extent permitted by law, the project operator excludes implied warranties and liability for investment loss, lost profits, lost data, business interruption, reliance on an output, third-party content or indirect/consequential loss. Nothing excludes liability that cannot legally be excluded, including liability for death or personal injury caused by negligence, fraud or fraudulent misrepresentation.</p>
  <h2>10. Privacy</h2><p>Account and technical information is handled as described in the Privacy and Data Usage Notice. Required authentication storage is described in the Cookie Notice.</p>
  <h2>11. Termination</h2><p>You may stop using the service at any time. The operator may disable an account for breach, risk, inactivity or project administration. Provisions concerning disclaimers, ownership, liability and governing law survive termination where applicable.</p>
  <h2>12. Changes and governing law</h2><p>The current version and date will be displayed, and users are asked to acknowledge it on login. These terms are governed by the laws of England and Wales; the courts of England and Wales have jurisdiction, subject to any mandatory consumer rights that apply.</p>
  <h2>13. Contact</h2><p>Questions should be directed to the project operator who issued the account credentials.</p>
</LegalPage>; }
